# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftVersion2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftVersion2
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
    pod 'RxOptional'

  target 'RxSwiftVersion2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftVersion2UITests' do
    # Pods for testing
  end

end
