# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestForRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'

  # Pods for TestForRxSwift

  target 'TestForRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RxBlocking', '6.2.0'
    pod 'RxTest', '6.2.0'

  end

  target 'TestForRxSwiftUITests' do
    # Pods for testing
  end

end
